public class SmartPhone extends Phone,MusicPlayer,Camera{
    // MULTIPLE INHERITANCE -- JAVA DO NOT ALLOW IT BECAUSE AMBIGUITY 
    // SMART PHONE CAN DO ALL WORK AND IF WE CALL A METHOD THAT IS PRESENT IN ALL THE SAME CLASS AND WHEN THE OBJECT IS CREATED OF THIS CLASS AND THEN CALLL A METHOD THAT IS PRESENT IN MULTIPLE CLASS THEN 
    // JAVA WILL CONFUSE WHICH METHOD TO CALL 
    // TO SOLVE THIS PROBLEM INTERFACE IS USED 
}